include :
    -   local : '.gitlab-release-branch.yml'

variables :
    RELEASE_VER : ${PKG_TAG_VERSION}
    GIT_CLONE_PATH : $CI_BUILDS_DIR/peek
    PEEK_NODE_VERSION : v7.1.0
    BUILD : build
    PKG_ENTERPRISE_LINUX : tmp_pkg_enterprise_linux
    PKG_COMMUNITY_LINUX : tmp_pkg_community_linux
    PKG_ENTERPRISE_MACOS : tmp_pkg_enterprise_macos
    PKG_COMMUNITY_MACOS : tmp_pkg_community_macos
    NON_RELEASE_VER : 0.0.0+b${CI_PIPELINE_ID}
    PINNED_DEPS_PY_FILE_CENTOS : ${CI_PROJECT_DIR}/gitlab/${RELEASE_BRANCH}/centos/pinned-deps-py
    PINNED_DEPS_PY_FILE_MACOS : ${CI_PROJECT_DIR}/gitlab/${RELEASE_BRANCH}/macos/pinned-deps-py

stages :
    - docs
    - fetch
    - publish
    - package
    - archive
    - upload


build_html_docs :
    artifacts :
        paths :
            - synerty-peek-html
        expire_in : 1 day
    allow_failure : false
    image : nexus.synerty.com:5000/peek-debian-doc:${RELEASE_BRANCH}
    only :
        - pushes
        - merge_requests
    script :
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - pip install -r docs/rtfd_requirements.txt
        - (cd docs && bash build_html_docs.sh)
        - mv docs/doc_dist synerty-peek-html
    stage : docs
    tags :
        - linux

build_latex_docs :
    artifacts :
        paths :
            - synerty-peek.pdf
        expire_in : 1 day
    allow_failure : false
    image : nexus.synerty.com:5000/peek-debian-doc:${RELEASE_BRANCH}
    only :
        - pushes
        - merge_requests
    script :
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - pip install -r docs/rtfd_requirements.txt
        - (cd docs && bash build_latex_docs.sh)
        - (cd docs/doc_dist_latex && pdflatex "SynertyPeek.tex")
        - mv docs/doc_dist_latex/SynertyPeek.pdf synerty-peek.pdf
    stage : docs
    tags :
        - linux

# ##########################################################################################
# # LINUX Builds

git_clone_community :
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/cloned_community_repos
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    script :
        - ./gitlab/scripts/git_clone.sh community ${GIT_CLONE_PATH}/cloned_community_repos
            ${GIT_USER} ${GIT_PASSWORD}
            ${CI_COMMIT_REF_NAME} ${CI_PROJECT_NAMESPACE} ${RELEASE_BRANCH}
    stage : fetch
    tags :
        - linux

git_clone_enterprise :
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/cloned_enterprise_repos
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    script :
        - ./gitlab/scripts/git_clone.sh enterprise ${GIT_CLONE_PATH}/cloned_enterprise_repos
            ${GIT_USER} ${GIT_PASSWORD}
            ${CI_COMMIT_REF_NAME} ${CI_PROJECT_NAMESPACE} ${RELEASE_BRANCH}
    stage : fetch
    tags :
        - linux

publish_community :
    dependencies :
        - git_clone_community
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/community_packages
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    stage : publish
    script :
        - export GITHUB_PUSH=0
        - pip install build
        - ./publish_community.sh ${RELEASE_VER:-${NON_RELEASE_VER}} ${GIT_CLONE_PATH}/cloned_community_repos
        - mkdir -p ${GIT_CLONE_PATH}/community_packages
        - mv ${GIT_CLONE_PATH}/cloned_community_repos/*/dist/* ${GIT_CLONE_PATH}/community_packages
    tags :
        - linux


publish_enterprise :
    dependencies :
        - git_clone_community
        - git_clone_enterprise
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/enterprise_packages
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    stage : publish
    script :
        - export GITHUB_PUSH=0
        - pip install build
        - ./publish_enterprise.sh ${RELEASE_VER:-${NON_RELEASE_VER}} ${GIT_CLONE_PATH}/cloned_enterprise_repos
        - mkdir -p ${GIT_CLONE_PATH}/enterprise_packages
        - mv ${GIT_CLONE_PATH}/cloned_enterprise_repos/*/dist/* ${GIT_CLONE_PATH}/enterprise_packages
    tags :
        - linux

package_community_linux :
    dependencies :
        - git_clone_community
        - publish_community
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/${PKG_COMMUNITY_LINUX}
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    stage : package
    script :
        - echo "registry=http://${NEXUS_URL}/repository/npm-all/:_auth" > ~/.npmrc
        - echo "_auth=$(echo -n "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64)"    >> ~/.npmrc
        - export NG_CLI_ANALYTICS=ci
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - export NPM_CONFIG_REGISTRY="http://${NEXUS_URL}/repository/npm-all/:_auth"
        - export NPM_CONFIG_AUTH=`echo "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64`
        - export NG_CLI_ANALYTICS=ci
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_COMMUNITY_LINUX}
        - ./scripts/linux/package_linux.sh -r community ${RELEASE_VER:-${NON_RELEASE_VER}}
            ${GIT_CLONE_PATH}/cloned_community_repos
            ${GIT_CLONE_PATH}/community_packages
            ${GIT_CLONE_PATH}/${PKG_COMMUNITY_LINUX}
            ${PINNED_DEPS_PY_FILE_CENTOS}
    tags :
        - linux

package_enterprise_linux :
    dependencies :
        - publish_community
        - publish_enterprise
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/${PKG_ENTERPRISE_LINUX}/
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    stage : package
    script :
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_ENTERPRISE_LINUX}
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - ./scripts/linux/package_linux.sh -r enterprise ${RELEASE_VER:-${NON_RELEASE_VER}}
            ${GIT_CLONE_PATH}/enterprise_packages
            ${GIT_CLONE_PATH}/community_packages
            ${GIT_CLONE_PATH}/${PKG_ENTERPRISE_LINUX}
            ${PINNED_DEPS_PY_FILE_CENTOS}
    tags :
        - linux

archive_release_linux :
    dependencies :
        - package_enterprise_linux
        - package_community_linux
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}.tar
        expire_in : 1 day
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    only :
        - web
        - triggers
    stage : archive
    script :
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}
        - cp ./scripts/linux/deploy_release_linux.sh
            ${GIT_CLONE_PATH}/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}
        - mv $GIT_CLONE_PATH/${PKG_COMMUNITY_LINUX}/peek_community_linux_${RELEASE_VER:-${NON_RELEASE_VER}}.tar.bz2
            ${GIT_CLONE_PATH}/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}
        - mv $GIT_CLONE_PATH/${PKG_ENTERPRISE_LINUX}/peek_enterprise_linux_${RELEASE_VER:-${NON_RELEASE_VER}}.tar.bz2
            ${GIT_CLONE_PATH}/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}
        - cd ${GIT_CLONE_PATH}
            && tar cvf peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}.tar
            peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}
        - rm -rf ${GIT_CLONE_PATH}/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}
    tags :
        - linux

upload_tagged_to_nexus_linux:
    dependencies:
        - archive_release_linux
    allow_failure: false
    image: nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    rules:
        - if: '$PKG_TAG_VERSION == null'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "web"'
        - if: '$CI_PIPELINE_SOURCE == "triggers"'
    script:
        - curl -v -u ${NEXUS_USER}:${NEXUS_PASSWORD}
            --upload-file $GIT_CLONE_PATH/peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}.tar
            http://${NEXUS_URL}/repository/synerty-packages/
    stage : upload
    tags :
        - linux

upload_master_to_nexus_linux:
    dependencies:
        - archive_release_linux
    allow_failure: false
    image: nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    rules:
        - if: '$CI_COMMIT_REF_NAME != $RELEASE_BRANCH'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "web"'
        - if: '$CI_PIPELINE_SOURCE == "triggers"'
    script:
        - cd $GIT_CLONE_PATH &&
            mv peek_release_linux_${RELEASE_VER:-${NON_RELEASE_VER}}.tar peek_release_linux_${RELEASE_BRANCH}.tar
        - curl -v -u ${NEXUS_USER}:${NEXUS_PASSWORD}
            --upload-file $GIT_CLONE_PATH/peek_release_linux_${RELEASE_BRANCH}.tar
            http://${NEXUS_URL}/repository/synerty-packages/
    stage: upload
    tags:
        - linux

##########################################################################################


package_community_macos :
    dependencies :
        - git_clone_community
        - publish_community
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/${PKG_COMMUNITY_MACOS}
        expire_in : 1 day
    rules :
        -   if : '$ENABLE_MACOS == null'
            when : never
        -   if : '$CI_PIPELINE_SOURCE == "web"'
        -   if : '$CI_PIPELINE_SOURCE == "triggers"'
    stage : package
    script :
        - echo "registry=http://${NEXUS_URL}/repository/npm-all/" > ~/.npmrc
        - echo "_auth=$(echo -n "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64)"    >> ~/.npmrc
        - export NG_CLI_ANALYTICS=ci
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - export NPM_CONFIG_REGISTRY="http://${NEXUS_URL}/repository/npm-all/"
        - export NPM_CONFIG_AUTH=`echo "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64`
        - export NG_CLI_ANALYTICS=ci
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_COMMUNITY_MACOS}
        - ./scripts/macos/package_macos.sh -r community ${RELEASE_VER:-${NON_RELEASE_VER}}
            ${GIT_CLONE_PATH}/cloned_community_repos
            ${GIT_CLONE_PATH}/community_packages
            ${GIT_CLONE_PATH}/${PKG_COMMUNITY_MACOS}
            ${PINNED_DEPS_PY_FILE_MACOS}
        - rm -rf ${GIT_CLONE_PATH}/community_packages
        - rm -rf ${GIT_CLONE_PATH}/cloned_community_repos
    tags :
        - macos

package_enterprise_macos :
    dependencies :
        - publish_community
        - publish_enterprise
    allow_failure : false
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/${PKG_ENTERPRISE_MACOS}/
        expire_in : 1 day
    rules :
        -   if : '$ENABLE_MACOS == null'
            when : never
        -   if : '$CI_PIPELINE_SOURCE == "web"'
        -   if : '$CI_PIPELINE_SOURCE == "triggers"'
    stage : package
    script :
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_ENTERPRISE_MACOS}
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-proxy/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - ./scripts/macos/package_macos.sh -r enterprise ${RELEASE_VER:-${NON_RELEASE_VER}}
            ${GIT_CLONE_PATH}/enterprise_packages ${GIT_CLONE_PATH}/community_packages
            ${GIT_CLONE_PATH}/${PKG_ENTERPRISE_MACOS} ${PINNED_DEPS_PY_FILE_MACOS}
    tags :
        - macos

archive_release_macos :
    dependencies :
        - package_enterprise_macos
        - package_community_macos
    allow_failure : false
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    artifacts :
        paths :
            - ${GIT_CLONE_PATH}/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}.tar
        expire_in : 1 day
    rules :
        -   if : '$ENABLE_MACOS == null'
            when : never
        -   if : '$CI_PIPELINE_SOURCE == "web"'
        -   if : '$CI_PIPELINE_SOURCE == "triggers"'
    stage : archive
    script :
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}
        - cp ./scripts/macos/deploy_release_macos.sh
            ${GIT_CLONE_PATH}/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}
        - mv $GIT_CLONE_PATH/${PKG_COMMUNITY_MACOS}/peek_community_macos_${RELEASE_VER:-${NON_RELEASE_VER}}.tar.bz2
            ${GIT_CLONE_PATH}/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}
        - mv $GIT_CLONE_PATH/${PKG_ENTERPRISE_MACOS}/peek_enterprise_macos_${RELEASE_VER:-${NON_RELEASE_VER}}.tar.bz2
            ${GIT_CLONE_PATH}/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}
        - cd ${GIT_CLONE_PATH}
            && tar cvf peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}.tar
            peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}
        - rm -rf ${GIT_CLONE_PATH}/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}
    tags :
        - linux

upload_to_nexus_macos :
    dependencies :
        - archive_release_macos
    allow_failure : false
    image : nexus.synerty.com:5000/peek-centos-build:${RELEASE_BRANCH}
    rules :
        -   if : '$ENABLE_MACOS == null'
            when : never
        -   if : '$PKG_TAG_VERSION == null'
            when : never
        -   if : '$CI_PIPELINE_SOURCE == "web"'
        -   if : '$CI_PIPELINE_SOURCE == "triggers"'
    script :
        - curl -v -u ${NEXUS_USER}:${NEXUS_PASSWORD}
            --upload-file $GIT_CLONE_PATH/peek_release_macos_${RELEASE_VER:-${NON_RELEASE_VER}}.tar
            http://${NEXUS_URL}/repository/synerty-packages/
    stage : upload
    tags :
        - linux


