variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/peek
    PEEK_NODE_VERSION: v7.1.0
    LATEST_NODE_VERSION: v12.16.1
    NVM_DIR: /usr/local/nvm
    BUILD: build
    PKG_PLUGIN_LINUX: tmp_pkg_plugin_linux
    PKG_PLATFORM_LINUX: tmp_pkg_platform_linux
    PEEK_RELEASE_LINUX: peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux

stages:
    - docs
    - fetch
    - publish
    - package
    - archive
    - upload


build_html_docs:
    artifacts:
        paths:
            - synerty-peek-html
        expire_in: 1 day
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux-docs
    only:
        - pushes
        - merge_requests
    script:
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - pip install -r docs/rtfd_requirements.txt
        - (cd docs && bash build_html_docs.sh)
        - mv docs/doc_dist synerty-peek-html
    stage: docs
    tags:
        - linux

build_latex_docs:
    artifacts:
        paths:
            - synerty-peek.pdf
        expire_in: 1 day
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux-docs
    only:
        - pushes
        - merge_requests
    script:
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - pip install -r docs/rtfd_requirements.txt
        - (cd docs && bash build_latex_docs.sh)
        - (cd docs/doc_dist_latex && pdflatex "SynertyPeek.tex")
        - mv docs/doc_dist_latex/SynertyPeek.pdf synerty-peek.pdf
    stage: docs
    tags:
        - linux


git_clone_platform:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/cloned_platform_repos
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    script:
        - ./scripts/gitlab/git_clone.sh platform ${GIT_CLONE_PATH}/cloned_platform_repos ${GIT_USER} ${GIT_PASSWORD} ${CI_COMMIT_REF_NAME} ${CI_PROJECT_NAMESPACE}
    stage: fetch
    tags:
        - linux

git_clone_plugins:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/cloned_plugin_repos
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    script:
        - ./scripts/gitlab/git_clone.sh plugins ${GIT_CLONE_PATH}/cloned_plugin_repos ${GIT_USER} ${GIT_PASSWORD} ${CI_COMMIT_REF_NAME} ${CI_PROJECT_NAMESPACE}
    stage: fetch
    tags:
        - linux

publish_platform:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/platform_packages
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    stage: publish
    script:
        - export GITHUB_PUSH=0
        - ./publish_platform.sh ${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}} ${GIT_CLONE_PATH}/cloned_platform_repos
        - mkdir -p ${GIT_CLONE_PATH}/platform_packages
        - mv ${GIT_CLONE_PATH}/cloned_platform_repos/*/dist/*.tar.gz ${GIT_CLONE_PATH}/platform_packages
    tags:
        - linux


publish_plugins:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/plugin_packages
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    stage: publish
    script:
        - export GITHUB_PUSH=0
        - ./publish_plugins.sh ${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}} ${GIT_CLONE_PATH}/cloned_plugin_repos
        - mkdir -p ${GIT_CLONE_PATH}/plugin_packages
        - mv ${GIT_CLONE_PATH}/cloned_plugin_repos/*/dist/*.tar.gz ${GIT_CLONE_PATH}/plugin_packages
    tags:
        - linux

package_platform_linux:
    dependencies:
        - git_clone_platform
        - publish_platform
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/${PKG_PLATFORM_LINUX}
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    stage: package
    script:
        - echo "registry=http://${NEXUS_URL}/repository/npm-all/" > ~/.npmrc
        - echo "_auth=$(echo -n "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64)"    >> ~/.npmrc
        - export NG_CLI_ANALYTICS=ci
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - export NPM_CONFIG_REGISTRY="http://${NEXUS_URL}/repository/npm-all/"
        - export NPM_CONFIG_AUTH=`echo "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64`
        - export NG_CLI_ANALYTICS=ci
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_PLATFORM_LINUX}
        - ./scripts/linux/package_platform_linux_gitlab.sh ${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}} ${GIT_CLONE_PATH}/cloned_platform_repos ${GIT_CLONE_PATH}/platform_packages ${GIT_CLONE_PATH}/${PKG_PLATFORM_LINUX}
        - rm -rf ${GIT_CLONE_PATH}/platform_packages
        - rm -rf ${GIT_CLONE_PATH}/cloned_platform_repos
    tags:
        - linux

package_plugin_linux:
    dependencies:
        - publish_platform
        - publish_plugins
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/${PKG_PLUGIN_LINUX}/
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    stage: package
    script:
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_PLUGIN_LINUX}
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - ./scripts/linux/package_plugins_linux_gitlab.sh ${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}} ${GIT_CLONE_PATH}/plugin_packages ${GIT_CLONE_PATH}/platform_packages ${GIT_CLONE_PATH}/${PKG_PLUGIN_LINUX}
    tags:
        - linux

archive_release:
    dependencies:
        - package_plugin_linux
        - package_platform_linux
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux.tar
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    stage: archive
    script:
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux
        - cp ./scripts/linux/deploy_release_linux.sh ${GIT_CLONE_PATH}/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux
        - mv $GIT_CLONE_PATH/${PKG_PLATFORM_LINUX}/peek_platform_linux_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}.tar.bz2 ${GIT_CLONE_PATH}/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux
        - mv $GIT_CLONE_PATH/${PKG_PLUGIN_LINUX}/peek_plugins_linux_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}.tar.bz2 ${GIT_CLONE_PATH}/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux
        - cd ${GIT_CLONE_PATH} && tar cvf peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux.tar peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux
        - rm -rf ${GIT_CLONE_PATH}/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux
    tags:
        - linux

upload_to_nexus:
    dependencies:
        - archive_release
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    script:
        - curl -v -u ${NEXUS_USER}:${NEXUS_PASSWORD} --upload-file $GIT_CLONE_PATH/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux.tar http://${NEXUS_URL}/repository/synerty-packages/

    stage: upload
    tags:
        - linux

upload_to_attune:
    dependencies:
        - archive_release
    allow_failure: false
    before_script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$DEPLOY_ATTUNE_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    environment:
        name: PEEK-RELEASE
    image: nexus.synerty.com:5000/peek-linux
    only:
        - web
        - triggers
    script:
        - scp $GIT_CLONE_PATH/peek_release_${PKG_TAG_VERSION:-0.0.0+b${CI_PIPELINE_ID}}_linux.tar ${DEPLOY_ATTUNE_USER}@${DEPLOY_ATTUNE_HOST}:gitlab_upload.tar
    stage: upload
    tags:
        - linux

