variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/peek
    PEEK_NODE_VERSION: v7.1.0
    LATEST_NODE_VERSION: v12.16.1
    NVM_DIR: /usr/local/nvm
    BUILD: build
    PKG_PLUGIN_LINUX: tmp_pkg_plugin_linux
    PKG_PLATFORM_LINUX: tmp_pkg_platform_linux
    PEEK_RELEASE_LINUX: peek_release_${PKG_TAG_VERSION}_linux

stages:
    - fetch
    - test
    - publish
    - package
    - archive
    - upload

git_clone_platform:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/cloned_platform_repos
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
        - merge_requests
        - manual
    script:
        - ./scripts/gitlab/git_clone.sh platform ${GIT_CLONE_PATH}/cloned_platform_repos ${GIT_USER} ${GIT_PASSWORD}
    stage: fetch
    tags:
        - linux

git_clone_plugins:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/cloned_plugin_repos
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
        - merge_requests
        - manual
    script:
        - ./scripts/gitlab/git_clone.sh plugins ${GIT_CLONE_PATH}/cloned_plugin_repos ${GIT_USER} ${GIT_PASSWORD}
    stage: fetch
    tags:
        - linux

unit_tests:
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
        - merge_requests
    script:
        - echo "Run unit tests"
    stage: test
    tags:
        - linux

sonar_platform:
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
        - merge_requests
    stage: test
    script:
        - echo "Run sonar-scanner"
        - source $NVM_DIR/nvm.sh
        - nvm use $LATEST_NODE_VERSION
        - export NODE_PATH=`npm root -g`
        - npm install -g typescript@3.7.5
        - ./scripts/gitlab/sonar_push.sh platform ${GIT_CLONE_PATH}/cloned_platform_repos
    tags:
        - linux

sonar_plugins:
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
        - merge_requests
    stage: test
    script:
        - echo "Run sonar-scanner"
        - source $NVM_DIR/nvm.sh
        - nvm use $LATEST_NODE_VERSION
        - export NODE_PATH=`npm root -g`
        - npm install -g typescript@3.7.5
        - ./scripts/gitlab/sonar_push.sh plugins ${GIT_CLONE_PATH}/cloned_plugin_repos
    tags:
        - linux

publish_platform:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/platform_packages
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
    stage: publish
    script:
        - export GITHUB_PUSH=0
        - ./publish_platform.sh $PKG_TAG_VERSION ${GIT_CLONE_PATH}/cloned_platform_repos
        - mkdir -p ${GIT_CLONE_PATH}/platform_packages
        - mv ${GIT_CLONE_PATH}/cloned_platform_repos/*/dist/*.tar.gz ${GIT_CLONE_PATH}/platform_packages
    tags:
        - linux


publish_plugins:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/plugin_packages
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
    stage: publish
    script:
        - export GITHUB_PUSH=0
        - ./publish_plugins.sh $PKG_TAG_VERSION ${GIT_CLONE_PATH}/cloned_plugin_repos
        - mkdir -p ${GIT_CLONE_PATH}/plugin_packages
        - mv ${GIT_CLONE_PATH}/cloned_plugin_repos/*/dist/*.tar.gz ${GIT_CLONE_PATH}/plugin_packages
#        - rm -rf ${GIT_CLONE_PATH}/cloned_plugin_repos
    tags:
        - linux

package_platform_linux:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/${PKG_PLATFORM_LINUX}
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
    stage: package
    script:
        - echo "registry=http://${NEXUS_URL}/repository/npm-all/" > ~/.npmrc
        - echo "_auth=$(echo -n "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64)"    >> ~/.npmrc
        - export NG_CLI_ANALYTICS=ci
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - export NPM_CONFIG_REGISTRY="http://${NEXUS_URL}/repository/npm-all/"
        - export NPM_CONFIG_AUTH=`echo "${NEXUS_USER}:${NEXUS_PASSWORD}" | openssl base64`
        - export NG_CLI_ANALYTICS=ci
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_PLATFORM_LINUX}
        - ./scripts/linux/package_platform_linux_gitlab.sh $PKG_TAG_VERSION ${GIT_CLONE_PATH}/cloned_platform_repos ${GIT_CLONE_PATH}/platform_packages ${GIT_CLONE_PATH}/${PKG_PLATFORM_LINUX}
        - rm -rf ${GIT_CLONE_PATH}/platform_packages
        - rm -rf ${GIT_CLONE_PATH}/cloned_platform_repos
    tags:
        - linux

package_plugin_linux:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/${PKG_PLUGIN_LINUX}/
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
    stage: package
    script:
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/${PKG_PLUGIN_LINUX}
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - ./scripts/linux/package_plugins_linux_gitlab.sh $PKG_TAG_VERSION ${GIT_CLONE_PATH}/plugin_packages ${GIT_CLONE_PATH}/platform_packages ${GIT_CLONE_PATH}/${PKG_PLUGIN_LINUX}
#        - rm -rf ${GIT_CLONE_PATH}/plugin_packages
    tags:
        - linux

archive_release:
    allow_failure: false
    artifacts:
        paths:
            - ${GIT_CLONE_PATH}/${PEEK_RELEASE_LINUX}.tar
        expire_in: 1 day
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
    stage: archive
    script:
        - mkdir -p ~/.config/pip
        - mkdir -p ${GIT_CLONE_PATH}/${PEEK_RELEASE_LINUX}
        - cp ./scripts/linux/deploy_release_linux.sh ${GIT_CLONE_PATH}/${PEEK_RELEASE_LINUX}
        - mv $GIT_CLONE_PATH/${PKG_PLATFORM_LINUX}/peek_platform_linux_${PKG_TAG_VERSION}.tar.bz2 ${GIT_CLONE_PATH}/${PEEK_RELEASE_LINUX}
        - mv $GIT_CLONE_PATH/${PKG_PLUGIN_LINUX}/peek_plugins_linux_${PKG_TAG_VERSION}.tar.bz2 ${GIT_CLONE_PATH}/${PEEK_RELEASE_LINUX}
        - cd ${GIT_CLONE_PATH} && tar cvf ${PEEK_RELEASE_LINUX}.tar ${PEEK_RELEASE_LINUX}
        - rm -rf ${GIT_CLONE_PATH}/${PEEK_RELEASE_LINUX}
    tags:
        - linux

upload_to_nexus:
    allow_failure: false
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
    script:
        - curl -v -u ${NEXUS_USER}:${NEXUS_PASSWORD} --upload-file $GIT_CLONE_PATH/${PEEK_RELEASE_LINUX}.tar http://${NEXUS_URL}/repository/synerty-packages/

    stage: upload
    tags:
        - linux

upload_to_attune:
    allow_failure: false
    before_script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$DEPLOY_ATTUNE_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    environment:
        name: PEEK-RELEASE
    image: nexus.synerty.com:5000/peek-linux
    only:
        - triggers
        - manual
    script:
        - scp $GIT_CLONE_PATH/${PEEK_RELEASE_LINUX}.tar ${DEPLOY_ATTUNE_USER}@${DEPLOY_ATTUNE_HOST}:gitlab_upload.tar
    stage: upload
    tags:
        - linux

